fornecedor/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('fornecedor/', views.cadastrarfornecedor, name= "cadastrarfornecedor"),
    path('listarfornecedor/', views.listarfornecedor, name='listarfornecedor'),
    path('editar_fornecedor/<int:fornecedor_id>/', views.editar_fornecedor, name='editar_fornecedor'),
    path('fornecedor/<int:fornecedor_id>/', views.exibirfornecedor, name="exibirfornecedor"),
    path('inativar_fornecedor/<int:fornecedor_id>/', views.inativar_fornecedor, name='inativar_fornecedor'),
     path('ativar_fornecedor/<int:fornecedor_id>/', views.ativar_fornecedor, name='ativar_fornecedor'),
   

    

]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name="home"),
    path('', views.login, name="login"),

]

projetoLagoinha/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('adminSuperupper/', admin.site.urls),
    path('estoque/', include ('estoque.urls')),
    path('fornecedor/', include ('fornecedor.urls')),
    path('', include ('home.urls')),
    path('user/', include ('user.urls')),
    path('saidas/', include ('saidas.urls')),
    path('entradas/', include ('entradas.urls')),
]


handler404 = "home.views.handler404"
handler403 = "home.views.handler403"
handler500 = "home.views.handler500"

fornecedor/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Fornecedor(models.Model):
    razaosocial = models.CharField(max_length=20)
    cnpj = models.CharField(max_length=14, blank=True)
    endereco = models.CharField(max_length=100)
    telefone = models.IntegerField()
    data = models.DateField(default=timezone.now)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return self.razaosocial 
    

fornecedor/forms.py
from django import forms
from .models import Fornecedor

class FornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedor
        fields = ['razaosocial', 'cnpj', 'telefone', 'data','endereco','ativo']

fornecedor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Fornecedor
from datetime import datetime
from django.db.models import Q
from django.contrib.auth.decorators import login_required


@login_required(login_url='login')
def cadastrarfornecedor(request): #cadastro do fornecedor
    fornecedores = Fornecedor.objects.all()
    
    if request.method == 'POST':
        razaosocial = request.POST.get('razaosocial', '').strip()
        cnpj = request.POST.get('cnpj', '').strip()
        telefone = request.POST.get('telefone', '').strip()
        endereco = request.POST.get('endereco', '').strip()

        try:
           
            if not razaosocial or razaosocial.isspace():
                raise ValueError("Razão social inválida!")

            
            cnpj = ''.join(char for char in cnpj if char.isdigit())
            if not cnpj.isdigit() or len(cnpj) != 14:
                raise ValueError("CNPJ inválido!")

          
            if not telefone.isdigit() or len(telefone) != 11:
                raise ValueError("Telefone inválido!")
            
            if not endereco or endereco.isspace():
                raise ValueError("Endereço inválido!")
            
            
            if Fornecedor.objects.filter(Q(razaosocial=razaosocial) | Q(cnpj=cnpj)).exists():
                raise ValueError("Razão social ou CNPJ já cadastrados!")

            # Obtém a data atual
            data = datetime.now()

            novo_fornecedor = Fornecedor(
                razaosocial=razaosocial,
                cnpj=cnpj,
                telefone=telefone,
                data=data,
                endereco=endereco,
            )

            novo_fornecedor.save()
            messages.success(request, "Fornecedor cadastrado com sucesso!")
            return redirect('listarfornecedor')

        except ValueError as e:
            messages.error(request, f"{e}")

    return render(request, 'fornecedor/cadastrarfornecedor.html', {'fornecedores': fornecedores})

@login_required(login_url='login')
def listarfornecedor(request):
    search_term = request.GET.get('search', '')
    fornecedores = Fornecedor.objects.all()

    if search_term:
        fornecedores = fornecedores.filter(Q(razaosocial__icontains=search_term) | Q(cnpj__icontains=search_term))

    return render(request, 'fornecedor/listarfornecedor.html', {'fornecedores': fornecedores, 'search_term': search_term})


@login_required(login_url='login')
def editar_fornecedor(request, fornecedor_id):
    fornecedor = get_object_or_404(Fornecedor, id=fornecedor_id)

    if request.method == 'POST':
        fornecedor.razaosocial = request.POST.get('razaosocial', '').strip()
        fornecedor.cnpj = request.POST.get('cnpj', '').strip()
        fornecedor.telefone = request.POST.get('telefone', '').strip()
        fornecedor.endereco = request.POST.get('endereco','').strip()
        
        fornecedor.save()
        messages.success(request, "Fornecedor editado com sucesso!")
        return redirect('listarfornecedor')
    
    
    
    return render(request, 'fornecedor/editar_fornecedor.html', {'fornecedor': fornecedor})

@login_required(login_url='login')
def exibirfornecedor(request,fornecedor_id): # Exibição de produto
    fornecedor = get_object_or_404(Fornecedor, id= fornecedor_id )  
    context = {
        'fornecedor': fornecedor, 
    }

    

    return render(request, 'fornecedor/exibirfornecedor.html', context)

@login_required(login_url='login')
def inativar_fornecedor(request, fornecedor_id): # Inativação do fornecedor
    fornecedor = get_object_or_404(Fornecedor, id=fornecedor_id)

    if request.method == 'POST':
        fornecedor.ativo = False
        fornecedor.save()
        messages.success(request, f"Fornecedor {fornecedor.razaosocial} inativado com sucesso!")
        return redirect('listarfornecedor')

    return render(request, 'fornecedor/inativar_fornecedor.html', {'fornecedor': fornecedor})

@login_required(login_url='login')
def ativar_fornecedor(request, fornecedor_id): # Ativação do fornecedor
    fornecedor = get_object_or_404(Fornecedor, id=fornecedor_id)
    fornecedor.ativo = True
    fornecedor.save()
    messages.success(request, f"Fornecedor {fornecedor.razaosocial} ativado com sucesso!")
    return redirect('listarfornecedor')

fornecedor/templates/fornecedor/cadastrarfornecedor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Cadastrar Fornecedor{% endblock title %}

{% block titulo %}
Cadastrar fornecedor
{% endblock titulo %}

{% block conteudo %}

  <form  method="POST" enctype="multipart/form-data" class="mt-4 ">
    {% csrf_token %}
    
    <div > 
      <div class="input-group mb-4">
        <label for="id_razaosocial"  class="col-sm-2 col-form-label" >Razão Social:</label>
        <input type="text" name="razaosocial" id="id_razaosocial" placeholder="Razão social" class="form-control"required>
      </div>

      <div class="input-group mb-4">
        <label for="id_cnpj"  class="col-sm-2 col-form-label">CNPJ:</label>
        <input type="text" name="cnpj" id="id_cnpj" placeholder="XXXXXXXXXXXXXX"class="form-control" required>
    </div>
    

      <div class="input-group mb-4">
        <label for="id_telefone"  class="col-sm-2 col-form-label" >Telefone:</label>
        <input type="text" name="telefone" id="id_telefone" placeholder="xxxxxxxxxxx"class="form-control" required>
      </div>

      <div class="input-group mb-4">
        <label for="id_endereco " class="col-sm-2 col-form-label">Endereço:</label>
        <input type="text" name="endereco" id="id_telefone" placeholder="Endereço"class="form-control" required>
      </div>

    </div >

    <div id="contforncedor">
      <button class="w-25 btn btn-lg btn-primary mx-auto"  type="submit">Cadastrar</button>
    </div>
    
  
</form>


{% endblock conteudo %}

fornecedor/templates/fornecedor/editar_fornecedor.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Editar Fornecedor{% endblock title %}

{% block titulo %}
    Editar fornecedor: {{ fornecedor.razaosocial }}
{% endblock titulo %}

{% block conteudo %}
    <form method="post" enctype="multipart/form-data" class="mt-4">
        {% csrf_token %}
        
        <div class="mb-3 row">
            <label for="razaoSocial" class="col-sm-2 col-form-label">Razão Social:</label>
            <div class="col-sm-10">
                <input type="text" id="razaoSocial" name="razaosocial" class="form-control" value="{{ fornecedor.razaosocial }}" required>
            </div>
        </div>

        <div class="mb-3 row">
            <label for="cnpj" class="col-sm-2 col-form-label">CNPJ:</label>
            <div class="col-sm-10">
                <input type="text" id="cnpj" name="cnpj" class="form-control" value="{{ fornecedor.cnpj }}" required>
            </div>
        </div>

        <div class="mb-3 row">
            <label for="telefone" class="col-sm-2 col-form-label">Telefone:</label>
            <div class="col-sm-10">
                <input type="text" id="telefone" name="telefone" class="form-control" value="{{ fornecedor.telefone }}" required>
            </div>
        </div>

        <div class="mb-3 row">
            <label for="endereco" class="col-sm-2 col-form-label">Endereço:</label>
            <div class="col-sm-10">
                <input type="text"  id="endereco" name="endereco" class="form-control" value="{{ fornecedor.endereco }}" required>
            </div>
        </div>

        <div class="btn-group btn_forn_edit d-flex justify-content-center" role="group" aria-label="Botões de Ação">
            {% if fornecedor.ativo %}
                <div id="contfornecedor2" class="mb-3 mx-3">
                    <a href="#" data-toggle="modal" data-target="#confirmarInativacaoModal" class="btn btn-lg btn-danger">Inativar</a>
                </div>
            {% else %}
                <div id="contfornecedor2" class="mb-3 mx-3">
                    <a href="#" onclick="ativarFornecedor()" class="btn btn-lg btn-success">Ativar</a>
                </div>
            {% endif %}
            
            <div id="contforncedor" class="mb-3">
                <button class="btn btn-lg btn-primary" type="submit">Salvar</button>
            </div>
        </div>
        
        
    <!-- Janela Modal de confirmação de inativação -->
    <div class="modal fade" id="confirmarInativacaoModal" tabindex="-1" role="dialog" aria-labelledby="confirmarInativacaoModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmarInativacaoModalLabel">Confirmação de Inativação</h5>
                </div>
                <div class="modal-body">
                    <p>Você tem certeza que deseja inativar o fornecedor {{ fornecedor.razaosocial }}?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" onclick="inativarFornecedor()">Confirmar Inativação</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>

    <!--Janela Modal de confirmação de ativação -->
    <div class="modal fade" id="confirmarAtivacaoModal" tabindex="-1" role="dialog" aria-labelledby="confirmarAtivacaoModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmarAtivacaoModalLabel">Confirmação de Ativação</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Você tem certeza que deseja ativar o fornecedor {{ fornecedor.razaosocial }}?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" onclick="confirmarAtivacao()">Confirmar Ativação</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" id="cancelarAtivacao">Cancelar</button>

                </div>
            </div>
        </div>
    </div>

    
</form>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
    function inativarFornecedor() {
        // vai fazer a inativação do fornecedor
        $.ajax({
            url: '{% url 'inativar_fornecedor' fornecedor.id %}',
            type: 'POST',
            data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
            success: function (data) {
             
                location.reload(); 
            },
            error: function (error) {
                console.log(error);
            }
        });
    }

    function ativarFornecedor() {
        // vai mostrar janela modal de confirmação de ativação
        $('#confirmarAtivacaoModal').modal('show');
    }

    function confirmarAtivacao() {
        // vai fazer a ativação do fornecedor
        $.ajax({
            url: '{% url 'ativar_fornecedor' fornecedor.id %}',
            type: 'POST',
            data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
            success: function (data) {
                // vai mostrar a janela modal de confirmação de ativação
                $('#confirmarAtivacaoModal').modal('hide'); 
                $('#confirmarAtivacaoSucessoModal').modal('show'); 
            },
            error: function (error) {
                console.log(error);
            }
        });
    }

 
    $('#confirmarAtivacaoModal').on('hidden.bs.modal', function (e) {
      
        $(this).off('hidden.bs.modal');
     
    });

    $('#cancelarAtivacao').on('click', function() {
       
        window.location.href = '{% url 'editar_fornecedor' fornecedor.id %}';

    });
</script>







{% endblock conteudo %}

fornecedor/templates/fornecedor/exibirfornecedor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Detalhes de fornecedor{% endblock title %}
{% block titulo %}
Detalhes do fornecedor: {{ fornecedor.razaosocial }}
{% endblock titulo %}
{% block conteudo %}
    <div class="card" id="det_forn">
        <div class="card-header text-white bg-dark">
            Fornecedor: {{ fornecedor.razaosocial }}
        </div>
        <div class="card-body">
            <h5 class="card-title mb-3"> Razão social: {{ fornecedor.razaosocial}}</h5>
            <h5 class="card-title mb-3">CNPJ: {{ fornecedor.cnpj}}</h5>
            <h5 class="card-title mb-3">Telefone:{{ fornecedor.telefone}}</h5>
            <h5 class="card-title mb-3">Endereço: {{ fornecedor.endereco }}</h5>
            <h5 class="card-title mb-3">Data de cadastro: {{ fornecedor.data }}</h5>
           

           
            <div class="card-footer text-white {% if fornecedor.ativo %}bg-success{% else %}bg-danger{% endif %}">
                Status: {% if fornecedor.ativo %}Ativo{% else %}Inativo{% endif %}
                
            </div>
            <div class="text-center mt-4 mb-2">
            <a href="{% url 'editar_fornecedor' fornecedor.id %}">
                <button type="button" class=" btn btn-secondary btn-sm">Editar</button>

            </div>
        </div>
    </div>

  
{% endblock conteudo %}

fornecedor/templates/fornecedor/listarfornecedor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Fornecedor{% endblock title %}

{% block titulo %}
    Meus fornecedores
{% endblock titulo %}

{% block conteudo %}
    <div class="buscarButtonColuna">
        <div class="buscarButton">
            <form class="row g-2 align-items-center" method="get" action="{% url 'listarfornecedor' %}">
                <div class="col-auto">
                    <input type="search" class="form-control mr-sm-2" name="search" autocomplete="off" placeholder="Pesquisar"> 
                </div>        
                <div class="col-auto">
                    <button class="btn btn-outline-success" type="submit">Pesquisar</button>
                </div>
            </form>
        </div>
        
     
        <div class='buttoncadastrar'>
            <div>
                <a href="{% url 'cadastrarfornecedor' %}"><button class="btn btn-success" type="button">Cadastrar</button></a>
            </div>
        </div>
    </div>

    <div class="table-content table-responsive text-center">
        <table class="table table-hover">
            <thead class="table-dark">
                <tr>
        
                    <th>Razão social</th>
                    <th>CNPJ</th>
                    <th>Status</th>
                    <th colspan="2">Operações</th>
                </tr>
            </thead>
            <tbody class='table-light'>
                {% for fornecedor in fornecedores %}
                    <tr>
                    
                        <td>{{ fornecedor.razaosocial }}</td>
                        <td>{{ fornecedor.cnpj }}</td>
                        <td>
                            {% if fornecedor.ativo %}
                                Ativo
                            {% else %}
                                <span class="text-danger">Inativo</span>
                            {% endif %}
                        </td>
                        <td><a href="{% url 'exibirfornecedor' fornecedor.id %}"><button type="button" class="btn btn-primary btn-sm">Exibir</button></a></td>
                        <td><a href="{% url 'editar_fornecedor' fornecedor.id %}"><button type="button" class="btn btn-secondary btn-sm">Editar</button></a></td>
                       
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock conteudo %}