estoque/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('cadastro/', views.add_produtos, name="add_produtos"),
    path('listar/', views.listaProdutos, name= "listaProdutos"),
    path('<int:produto_id>/<int:fornecedor_id>/', views.prod_exibir, name="prod_exibir"),
    path('editar/<int:produto_id>', views.editarProdutos, name="editarProdutos"),
  
    path('categorias/cadastro/', views.cadastrarCategorias, name="cadastro_categorias"),
    path('categorias/', views.listaCategorias, name='listagem_categorias'),
    path('categorias/editar/<int:categoria_id>/', views.cat_editar, name='editar_categorias'),
    path('categorias/excluir/<int:id>/', views.cat_excluir, name='excluir_categorias'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name="home"),
    path('', views.login, name="login"),

]

projetoLagoinha/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('adminSuperupper/', admin.site.urls),
    path('estoque/', include ('estoque.urls')),
    path('fornecedor/', include ('fornecedor.urls')),
    path('', include ('home.urls')),
    path('user/', include ('user.urls')),
    path('saidas/', include ('saidas.urls')),
    path('entradas/', include ('entradas.urls')),
]


handler404 = "home.views.handler404"
handler403 = "home.views.handler403"
handler500 = "home.views.handler500"

estoque/models.py
from django.db import models
from django.contrib.auth.models import User
from fornecedor.models import Fornecedor


# Create your models here.
    
class Categoria(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome 
    
class Produto(models.Model):
    nome = models.CharField(max_length=20)
    ncm = models.CharField(max_length=20)
    categoria = models.ForeignKey(
        Categoria, on_delete=models.PROTECT)
    preco = models.FloatField(blank=True)
    precovenda =  models.FloatField(blank=True)
    estoque = models.IntegerField(blank=True) #mudar pra quantidade
    estoquemin = models.IntegerField(blank=True)
    descricao = models.TextField(default='Sem descrição', null=True)
    usuario = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )
    fornecedor = models.ForeignKey(
        Fornecedor, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.nome 
    

estoque/forms.py
from django import forms
from .models import Produto

class ProdutosForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'ncm', 'categoria', 'preco', 'precovenda', 'estoque', 'estoquemin', 'usuario', 'fornecedor']

estoque/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Categoria,Produto, Fornecedor
from decimal import Decimal
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models import ProtectedError
from rolepermissions.decorators import has_permission_decorator, has_role_decorator


@login_required(login_url='login')
@login_required
def add_produtos(request): # Cadastrar produto
    categorias = Categoria.objects.all()
    fornecedores = Fornecedor.objects.filter(ativo=True)
    user = request.user

    if request.method == 'POST':
        nome = request.POST.get('nome', '').strip()
        preco = request.POST.get('preco', '0').replace(',', '.')  # vai substituir a vírgula por ponto
        precovenda = request.POST.get('precovenda', '0').replace(',', '.')  
        estoquemin_str = request.POST.get('estoquemin', '0').replace(',', '.')  
        ncm = request.POST.get('ncm', '')
        descricao = request.POST.get('descricao', '').strip() 

        try:
            # Vai converter os números de string para decimal ou inteiro
            preco_decimal = Decimal(preco)
            precovenda_decimal = Decimal(precovenda)
            estoquemin_float = float(estoquemin_str)

            # Verifica se a quantidade mínima é um número inteiro
            if estoquemin_float.is_integer():
                estoquemin_int = int(estoquemin_float)
            else:
                raise ValueError("A quantidade mínima deve ser um número inteiro.")

            if preco_decimal <= Decimal('0'):
                messages.error(request, "O preço deve ser maior que zero.")
            elif descricao == "" or descricao.isspace():
                messages.error(request, "Descrição inválida!")
            elif nome == "" or nome.isspace():
                messages.error(request, "Nome inválido!")
            elif precovenda_decimal <= Decimal('0'):
                messages.error(request, "O preço de venda deve ser maior que zero.")
            elif estoquemin_int <= 0:
                messages.error(request, "O estoque mínimo deve ser maior que zero.")
            else:
                categoria_id = request.POST.get('categoria')
                categoria = get_object_or_404(Categoria, pk=categoria_id)

                fornecedor_id = request.POST.get('fornecedor')
                fornecedor = get_object_or_404(Fornecedor, pk=fornecedor_id)

                # Vai definir que a quantidade padrão ao criar um novo produto será "0"
                quantidade_padrao = 0

                novo_cadastro = Produto(
                    nome=nome,
                    preco=preco_decimal,
                    precovenda=precovenda_decimal,
                    estoque=quantidade_padrao,
                    estoquemin=estoquemin_int,
                    categoria=categoria,
                    fornecedor=fornecedor,
                    ncm=ncm,
                    descricao=descricao,
                    usuario=user
                )
                novo_cadastro.save()

                messages.success(request, "Produto cadastrado com sucesso!")
                return redirect('listaProdutos')

        except ValueError as e:
            messages.error(request, f" {e}")
            return redirect('add_produtos')

    return render(request, 'estoque/add_produtos.html', {'categorias': categorias, 'fornecedores': fornecedores})


@login_required(login_url='login')
def prod_exibir(request, produto_id,fornecedor_id): # Exibição de produto
    produto = get_object_or_404(Produto, id=produto_id)
    fornecedor = get_object_or_404(Fornecedor, id= fornecedor_id )  
    context = {
        'produto': produto,
        'fornecedor': fornecedor, 
    }

    return render(request, 'estoque/prod_exibir.html', context)


@login_required(login_url='login')
def listaProdutos(request): # Listagem de produto
    produtos = Produto.objects.all()
    if request.GET.get('pesquisa'):
        pesq = request.GET.get('pesquisa')
        produtos = produtos.filter(Q(nome__icontains=pesq)).order_by('-id')
    else:
        produtos = Produto.objects.order_by('-id').filter
    contexto = {
        'produtos': produtos,
    } 
    return render(request, 'estoque/listaProdutos.html', contexto)


@login_required(login_url='login')
def editarProdutos(request, produto_id):  # Editar produto
    produto = get_object_or_404(Produto, pk=produto_id)
    categorias = Categoria.objects.all()
    fornecedores = Fornecedor.objects.filter(ativo=True)

    if request.method == 'POST':
        produto.nome = request.POST.get('nome', '')
        produto.descricao = request.POST.get('descricao', '')
        preco_str = request.POST.get('preco', '')
        precovenda_str = request.POST.get('precovenda', '')
        estoquemin_str = request.POST.get('estoquemin', '0').replace(',', '.')
        ncm = request.POST.get('ncm', '')

        categoria_id = request.POST.get('categoria')
        fornecedor_id = request.POST.get('fornecedor')

        try:
            # Validação e conversão de preços e estoquemin
            preco_str = preco_str.replace(',', '.')
            precovenda_str = precovenda_str.replace(',', '.')
            produto.preco = Decimal(preco_str)
            produto.precovenda = Decimal(precovenda_str)
            produto.estoquemin = int(estoquemin_str)

            # Validação e atribuição de categoria
            categoria = get_object_or_404(Categoria, pk=categoria_id)
            produto.categoria = categoria

            # Validação e atribuição de fornecedor
            fornecedor = get_object_or_404(Fornecedor, pk=fornecedor_id)
            produto.fornecedor = fornecedor

            produto.ncm = ncm
            produto.save()

            messages.success(request, "Produto editado com sucesso!")
            return redirect('listaProdutos')

        except( ValueError, Fornecedor.ObjectDoesNotExist) as e:
            messages.error(request, f"Erro ao editar o produto: {e}")

    return render(request, 'estoque/editarProdutos.html', {'produto': produto, 'categorias': categorias, 'fornecedores': fornecedores})



@login_required(login_url='login')
def cadastrarCategorias(request): # cadastro de categoria
    if request.method == 'POST':
        nome = request.POST.get('nome').strip()
        
        if nome == "":
            messages.error(request, "Nome inválido!")
            return render(request, 'estoque/add_categoria.html')             
        nova_categoria = Categoria(
            nome=nome)
        nova_categoria.save()
        messages.success(request, "Categoria cadastrada com sucesso!")
        return redirect('listagem_categorias')
    return render(request, 'estoque/add_categoria.html')


@login_required(login_url='login')
def listaCategorias(request): #listagem de categorias
    categorias = Categoria.objects.all()
    if request.GET.get('pesquisa'):
        pesq = request.GET.get('pesquisa')
        categorias = categorias.filter(Q(nome__icontains=pesq)).order_by('-id')
    else:
        categorias = Categoria.objects.order_by('-id').filter
    contexto = {
        'categorias': categorias,
    } 
    return render(request, 'estoque/cat_listagem.html', contexto)



@login_required(login_url='login')
def cat_editar(request, categoria_id): #editar de categorias
    categoria = get_object_or_404(Categoria, pk=categoria_id)
    contexto = {
        'categoria': categoria
    }
    if request.method == "POST":
        nome = request.POST.get('nome').strip()

        if nome == "":
            messages.error(request, "Nome inválido!")
            return render(request, 'estoque/cat_editar.html', contexto)             
          
        categoria.nome = nome
        categoria.save()
        messages.success(request, "Categoria editada com sucesso!")
        return redirect('listagem_categorias')
    return render(request, 'estoque/cat_editar.html', contexto)

  
@has_permission_decorator('ex_cat')
def cat_excluir(request, id):
    categoria = get_object_or_404(Categoria, pk=id)
    if request.method == 'POST':
        try:
            categoria.delete()
            messages.success(request, "Categoria deletada com sucesso!")
            return redirect('listagem_categorias')
        except ProtectedError:
            messages.error(request, "Você não pode excluir uma categoria que está cadastrada em um produto.")
    contexto = {
        'categoria': categoria
    }
    return render(request, 'estoque/excluir.html', contexto)  

estoque/templates/estoque/add_categoria.html
{% extends 'base.html' %}
{% load static %}
{%block title %}Categorias{%endblock title %}

{%block titulo %}
Cadastrar Categoria
{%endblock titulo %}

{% block conteudo %}
<form class="mt-4" enctype="multipart/form-data" method="post" action="{% url 'cadastro_categorias' %}">
    {% csrf_token %}

    
    <div class="input-group mb-4">
        <span  class="col-sm-2 col-form-label">Nome</span>
        <input  type="text" id="cat_nome" name='nome' placeholder="Nome da categoria" class="form-control" style="color: black !important;" required>>
    </div>
    <div id="contforncedor">
        <button class="w-25 btn btn-lg btn-primary mx-auto" type="submit">Cadastrar</button>
    </div>
</form>

{% endblock conteudo %}

estoque/templates/estoque/add_produtos.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Produtos{% endblock title %}

{% block titulo %}
Cadastrar Produto
{% endblock titulo %}

{% block conteudo %}
    <form  method="POST" enctype="multipart/form-data" class="mt-4">
        {% csrf_token %}

        <div class="input-group mb-4">
            <label for="nome" class="col-sm-2 col-form-label">Nome:</label>
            <input type="text" id="nome" name='nome' placeholder="Nome do produto" class="form-control" style="color: black !important;" required>

        </div>

        <div class="input-group mb-4">
            <label for="preco" class="col-sm-2 col-form-label">Preço:</label>
            <input type="text" id="preco" name='preco' placeholder="Preço" class="form-control"style="color: black !important;" required>
        </div>

        <div class="input-group mb-4">
            <label for="precovenda" class="col-sm-2 col-form-label">Preço de venda:</label>
            <input type="text" id="precovenda" name='precovenda' placeholder="Preço de venda" class="form-control " style="color: black !important;" required>
        </div>

        <div class="input-group mb-4">
            <label for="fornecedor" class="col-sm-2 col-form-label">Fornecedor:</label>
            <select id="fornecedor" name="fornecedor" class="form-control " style="color: black !important;" required>
                {% for fornecedor in fornecedores %}
                    <option value="{{ fornecedor.id }}">{{ fornecedor.razaosocial }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="input-group mb-4">
            <label for="estoquemin" class="col-sm-2 col-form-label">Mínimo:</label>
            <input type="text" id="estoquemin" name='estoquemin' placeholder="Quant. Mínima" class="form-control " style="color: black !important;" required>
        </div>

        <div class="input-group mb-4">
            <label for="categoria" class="col-sm-2 col-form-label">Categoria:</label>
            <select id="categoria" name="categoria" class="form-control" style="color: black !important;" required>
                {% for categoria in categorias %}
                    <option value="{{ categoria.id }}">{{ categoria.nome }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="input-group mb-4">
            <label for="descricao" class="col-sm-2 col-form-label">Descrição:</label>
            <textarea id="descricao" name="descricao" placeholder="Descrição do produto" class="form-control " style="color: black !important;" required></textarea>
        </div>

        <div class="input-group mb-4">
            <label for="ncm" class="col-sm-2 col-form-label">NCM:</label>
            <input type="text" name='ncm' id="ncm" placeholder="Código do produto" class="form-control " style="color: black !important;" required>
        </div>

        <div id="contforncedor">
            <button class="w-25 btn btn-lg btn-primary mx-auto" type="submit">Cadastrar</button>
        </div>
    </form>
{% endblock conteudo %}

estoque/templates/estoque/cat_editar.html
{% extends 'base.html' %}
{% load static %}
{%block title %}Categorias{%endblock title %}

{%block titulo %}
Editar Categoria {{ categoria.id }}
{%endblock titulo %}

{% block conteudo %}


    <form class="mt-4" enctype="multipart/form-data" method="post" action="{% url 'editar_categorias' categoria.id %}">
        {% csrf_token %}
        
        <div class="input-group mb-4">
            <label for="nome" class="col-sm-2 col-form-label">Nome:</label>
            <input type="text" id="id_nome" name='nome'  value="{{ categoria.nome}}" class="form-control" style="color: black !important;" required>

        </div>

        <div id="contforncedor"> 
        <button  class="w-25 btn btn-lg btn-primary mx-auto" type="submit">Salvar</button>
        </div>
    </form>

{% endblock conteudo %}

estoque/templates/estoque/cat_listagem.html
{% extends 'base.html' %}
{% load static %}
{% load permission_tags %}
{%block title %}Categorias{%endblock title %}

{%block titulo %}
Minhas Categorias

{%endblock titulo %}

{% block conteudo %}

<div class="buscarButtonColuna">

        <div class="buscarButton">
                <form class="row g-2 align-items-center">
                        <div class="col-auto">
                                <input type="search" class="form-control mr-sm-2" autocomplete="off"  placeholder="pesquisa" name="pesquisa"> 
                        </div>        
                        <div class="col-auto">
                                <button class="btn btn-outline-success" type="submit">Pesquisar</button>
                        </div>
                </form>
                </div>
        
        <div class='buttoncadastrar'>

        <div>
        
                <a href="{% url "cadastro_categorias" %}">&nbsp;<button class="btn btn-success" type="button">Cadastrar</button><a/>
        </div>

        </div>
</div>


<div class="table-content table-responsive text-center">
        <table class="table table-hover">
                <thead class="table-dark">
                        <tr>
                                <th>Nome</th>
                                <th colspan="3" class="text-md-center">Operações</th>
                        </tr>
                </thead>
                <tbody class='table-light'>
                    {% for categoria in categorias %}
                    <tr>
                            <td>{{categoria.nome}}</td>
                            <td><a href="{% url "editar_categorias" categoria.id %}"><button type="button" class="btn btn-secondary btn-sm">Editar</button></a></td>
                            {%if user|can:"ex_cat"%}
                            <td><a href ="{% url "excluir_categorias" categoria.id %}"><button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">Remover</button></a></td>
                            {%else%}
                            <td><p>:)</p></td>
                            {% endif %}

                                
                        
                       </div>
                    </tr>
                    
                    {% endfor %}
                </tbody>
        </table>
</div>
{% endblock conteudo %}

estoque/templates/estoque/editarProdutos.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Editar produto{% endblock title %}
{% block titulo %}
Editar produto: {{ produto.nome }}
{% endblock titulo %}
{% block conteudo %}

<form method="post" enctype="multipart/form-data" class="mt-4">
    {% csrf_token %}
    
    <div class="input-group mb-4">
        <span id="basic-addon1" class="col-sm-2 col-form-label">Nome:</span>
        <input type="text" name='nome' value="{{ produto.nome }}" class="form-control" required>
    </div>

    <div class="input-group mb-4">
        <span id="basic-addon1" class="col-sm-2 col-form-label">Descrição:</span>
        <input type="text" name='descricao' value="{{ produto.descricao }}" class="form-control" required>
    </div>

    <div class="input-group mb-4">
        <span id="basic-addon1" class="col-sm-2 col-form-label">Preço:</span>
        <input type="text" name='preco' value="{{ produto.preco }}" class="form-control" required>
    </div>

    <div class="input-group mb-4">
        <span id="basic-addon1" class="col-sm-2 col-form-label">Preço de venda:</span>
        <input type="text" name='precovenda' value="{{ produto.precovenda }}" class="form-control" required>
    </div>

    <!-- Adicione os campos adicionais aqui -->
    <div class="input-group mb-4">
        <span id="basic-addon1" class="col-sm-2 col-form-label">Estoque Mínimo:</span>
        <input type="text" name='estoquemin' value="{{ produto.estoquemin }}" class="form-control" required>
    </div>

    <div class="input-group mb-4">
        <span id="basic-addon1" class="col-sm-2 col-form-label">NCM:</span>
        <input type="text" name='ncm' value="{{ produto.ncm }}" class="form-control" required>
    </div>

    <div class="input-group mb-4">
        <span id="basic-addon1" class="col-sm-2 col-form-label">Categoria:</span>
        <select name="categoria" class="form-select" required>
            {% for categoria in categorias %}
                <option value="{{ categoria.id }}" {% if categoria.id == produto.categoria.id %}selected{% endif %}>{{ categoria.nome }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="input-group mb-4">
        <span id="basic-addon1" class="col-sm-2 col-form-label">Fornecedor:</span>
        <select name="fornecedor" class="form-select" required>
            {% for fornecedor in fornecedores %}
                <option value="{{ fornecedor.id }}" {% if fornecedor.id == produto.fornecedor.id %}selected{% endif %}>{{ fornecedor.razaosocial }}</option>
            {% endfor %}
        </select>
    </div>

    <div id="contforncedor">
        <button class="w-25 btn btn-lg btn-primary mx-auto" type="submit">Salvar</button>
    </div>
</form>
{% endblock conteudo %}

estoque/templates/estoque/excluir.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Categoria {% endblock title %}

{% block titulo %}Excluir Categoria{% endblock titulo %}

{% block conteudo %}
        <form id="form_del" method="POST">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{categoria.id}}">
        </form>
            <hr>
            <div class="saidaexclusao">
            <p class="p_excluir">Deseja realmente excluir a Categoria?</p><br>
                <a href="{% url 'saidas' %}">
                    <button type="button" class="btn btn-secondary btn-sm">Cancelar</button>
                </a>
                <input form="form_del" type="submit" class="btn btn-danger btn-sm" value="Excluir">
            </div>



{% endblock conteudo %}

estoque/templates/estoque/listaProdutos.html
{% extends 'base.html' %}
{% load static %}
{%block title %}Produtos{%endblock title %}

{%block titulo %}
Meus Produtos

{%endblock titulo %}

{% block conteudo %}
<div class="buscarButtonColuna">

        <div class="buscarButton">
        <form class="row g-2 align-items-center">
                <div class="col-auto">
                        <input type="search" class="form-control mr-sm-2" autocomplete="off"  placeholder="Pesquisar" name="pesquisa"> 
                </div>        
                <div class="col-auto">
                        <button class="btn btn-outline-success" type="submit">Pesquisar</button>
                </div>
        </form>
        </div>

        <div class='buttoncadastrar'>

        <div><a href="{%url 'add_produtos'%}"><button class="btn btn-success" type="button">Cadastrar Produto</button><a/>
        
            <a href="{% url 'listagem_categorias' %}"><button class="btn btn-primary" type="button">Categoria</button></a>

            <a href="{% url 'listarfornecedor' %}"><button class="btn btn-primary" type="button">Fornecedor</button></a>



        </div>

        </div>
        </div>

        <div class="table-content table-responsive text-center">

                <table class="table table-hover">
                        <thead class="table-dark">
                            <tr>
                                <th>Nome</th>
                                <th>Status</th>
                                <th>Preço</th>
                                <th>Descrição</th>
                                <th colspan="2">Operações</th>
                            </tr>
                        </thead>

                        <tbody class='table-light'>
                            {% for produto in produtos %}
                                <tr>
                                    <td>{{ produto.nome }}</td>
                                    <td>
                                        {% if produto.estoque == 0 %}
                                            Esgotado
                                        {% elif produto.estoque <= produto.estoquemin %}
                                            Disponível (Abaixo da Quantidade Mínima)
                                        {% else %}
                                            Disponível
                                        {% endif %}
                                    </td>
                                    <td>{{ produto.precovenda }}</td>
                                    <td>{{ produto.descricao }}</td>
                                    <td>
                                        {% if produto.fornecedor and produto.fornecedor.id %}
                                            <a href="{% url 'prod_exibir' produto.id produto.fornecedor.id %}">
                                                <button type="button" class="btn btn-primary btn-sm">Exibir</button>
                                            </a>
                                        {% endif %}
                                    </td>
                                    
                                    <td><a href="{% url 'editarProdutos' produto.id %}" class="btn btn-secondary btn-sm">Editar</a></td>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
        </div>
{% endblock conteudo %}

estoque/templates/estoque/prod_exibir.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Detalhes do Produto{% endblock title %}
{% block titulo %}
Detalhes do produto: {{ produto.nome }}
{% endblock titulo %}
{% block conteudo %}
    <div class="card">
        <div class="card-header text-white bg-dark">
                Categoria: {{ produto.categoria.nome }}
        </div>
        <div class="card-body">
            <h5 class="card-title mb-3"> Nome: {{ produto.nome }}</h5>
            <h5 class="card-title mb-3">Preço: R$ {{ produto.preco|floatformat:2 }}</h5>
            <h5 class="card-title mb-3">Preço de venda: R$ {{ produto.precovenda|floatformat:2 }}</h5>
            <h5 class="card-title mb-3">Quantidade no Estoque: {{ produto.estoque }}</h5>
            <h5 class="card-title mb-3">Quantidade Mínima: {{ produto.estoquemin }}</h5>
            <h5 class="card-text"> Descrição: {{ produto.descricao }}</h5>
            <h5 class="card-title mb-3">NCM: {{produto.ncm}}</h5>
            <h5 class="card-title mb-3">Fornecedor:{{ fornecedor.razaosocial}} </h5>
            <h5 class="card-title mb-3">Cadastrado por: {{ produto.usuario}} </h5>
        </div>
        
        <div class="card-footer text-white {% if produto.estoque == 0 %}bg-danger{% elif produto.estoque <= produto.estoquemin %}bg-warning{% else %}bg-success{% endif %}">
            Status: {% if produto.estoque == 0 %}Esgotado{% elif produto.estoque <= produto.estoquemin %}Abaixo da Quantidade Mínima{% else %}Disponível{% endif %}
        </div>
        <div class="text-center mt-4 mb-2">
            <a href="{% url 'editarProdutos' produto.id %}" class=" btn btn-secondary btn-sm">Editar</a>
        </div>
    </div>
{% endblock conteudo %}